auth_enabled: false

server:
    http_listen_port: 3100
    grpc_listen_port: 9096

ingester:
    wal:
        enabled: true
        dir: /loki/wal
    lifecycler:
        address: 127.0.0.1
        ring:
            kvstore:
                store: inmemory
            replication_factor: 1
        final_sleep: 0s
    chunk_idle_period: 1h
    max_chunk_age: 1h
    chunk_target_size: 1048576
    chunk_retain_period: 30s
    max_transfer_retries: 0

storage_config:
    filesystem:
        directory: /loki/chunks

schema_config:
    configs:
      - from: 2019-01-01
        object_store: filesystem
        store: tsdb
        schema: v13
        index:
            prefix: index_
            period: 24h

limits_config:
    enforce_metric_name: false
    max_cache_freshness_per_query: 10m
    max_query_length: 12000h
    max_query_parallelism: 256
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    retention_period: 336h
    ingestion_rate_mb: 50
    ingestion_burst_size_mb: 60
    per_stream_rate_limit: 5MB
    per_stream_rate_limit_burst: 20MB
    split_queries_by_interval: 15m
    unordered_writes: true

common:
    instance_addr: 127.0.0.1
    path_prefix: /loki
    storage:
        filesystem:
            chunks_directory: /loki/chunks
            rules_directory: /loki/rules
    replication_factor: 1
    ring:
        kvstore:
            store: inmemory

query_range:
    align_queries_with_step: true
    parallelise_shardable_queries: true
    max_retries: 5
    cache_results: true
    results_cache:
        cache:
            embedded_cache:
                enabled: true
                max_size_mb: 100

frontend:
    log_queries_longer_than: 5s
    compress_responses: true
    max_outstanding_per_tenant: 2048

query_scheduler:
    max_outstanding_requests_per_tenant: 1024

querier:
    query_ingesters_within: 2h

ruler:
    alertmanager_url: http://alertmanager:9093

analytics:
    reporting_enabled: false
