global:
    scrape_interval: 15s
    evaluation_interval: 15s

    # Attach these labels to any time series or alerts when communicating with
    # external systems (federation, remote storage, Alertmanager).
    external_labels:
        monitor: "docker-host-alpha"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
    - "rule.containers.yml"
    - "rule.cpu_thresholds.yml"
    - "rule.storage_thresholds.yml"
    - "rule.memory_thresholds.yml"
    - "rule.instance_shutdown.yml"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
    - job_name: "nodeexporter"
      static_configs:
          - targets: ["nodeexporter:9100"]

    - job_name: "cadvisor"
      static_configs:
          - targets: ["cadvisor:8080"]

    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: blackbox
      scrape_interval: 60s
      metrics_path: /metrics
      static_configs:
          - targets: ["blackboxexporter:9115"]

    - job_name: blackbox-http
      scrape_interval: 60s
      metrics_path: /probe
      params:
          module: [http_2xx]
      static_configs:
          - targets:
             - http://google.gr
             - https://google.gr
      relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackboxexporter:9115

#  - job_name: 'nginx'
#    static_configs:
#      - targets: ['nginxexporter:9113']

alerting:
    alertmanagers:
        - scheme: http
          static_configs:
              - targets: ["alertmanager:9093"]
