{
 "title": "NGINX",
 "description": "Nginx access log analytics.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({job=\"nginx\", filename=\"$host\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(rate({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | status >= 500 | __error__=\"\"[$__interval])) / (sum(rate({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\"[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "% of Unauthenticated requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(rate({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | status = 403 | __error__=\"\"[$__interval])) / (sum(rate({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\"[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (host) (max_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | unwrap request_time |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\" [1h])))"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\" [1d])))"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\" [2d])))"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\" [7d])))"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\" [1d])))",
     "legendFormat": "Unique user visit count"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 17, "w": 14, "x": 10, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=`` | line_format `request for {{.request_uri}} with HTTP status: {{.status}} from {{.remote_addr}}`"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\" [30d])))",
     "legendFormat": "Unique user visit count"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 27, "w": 9, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "topk(5, sum by (remote_addr) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers - Exclude Panxora Site",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 41 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_referer) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\" [$__interval]))) ",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top Requested Pages - Excluding '/'",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 47 },
   "targets": [
    {
     "expr": "topk(10,sum by (request_uri) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\" [$__interval])))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 55 },
   "targets": [
    {
     "expr": "topk(5, sum by (http_referer) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 61 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_user_agent) (count_over_time({job=\"nginx\", filename=\"$host\"} | json | request_uri !~ `/grafana.*` | http_user_agent !~ `^Blackbox Exporter.*` | __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  }
 ]
}