apiVersion: 1

datasources:
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      url: http://loki:3100
      jsonData:
          timeout: 60
          maxLines: 1000
      basicAuth: false
      isDefault: false
      editable: true
